name: miuzik
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-232.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: 2.0.3
  supabase_flutter: 0.3.1+3
  flutter_dotenv: 5.0.2
  flutter_neumorphic: 3.2.0
  flutter_screenutil: 5.5.3+2
  glassmorphism_widgets: 0.1.1
  lottie: 1.3.0
  line_icons: 2.0.1

dev_dependencies: 
  very_good_analysis: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - .env
    - assets/
    - assets/lottie/
  uses-material-design: true

